# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tidytuesday005',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/tidytuesday005',
                'lib_path': 'tidytuesday005'},
  'syms': {'tidytuesday005.core': {'tidytuesday005.core.foo': ('core.html#foo', 'tidytuesday005/core.py')}}}
